ARG FROM_IMAGE
FROM $FROM_IMAGE

ARG XDEBUG_PKG=php8-pecl-xdebug

RUN \
  apk add --no-cache \
    ${XDEBUG_PKG} && \
  mv \
    /defaults/php/conf.d/xdebug.ini.sample \
    /etc/php/conf.d/xdebug.ini
