ARG FROM_IMAGE
FROM $FROM_IMAGE

ARG XDEBUG_PKG

RUN \
  apk add --no-cache \
    ${XDEBUG_PKG} && \
  mv \
    /defaults/php/conf.d/xdebug.ini.sample \
    /etc/php/conf.d/xdebug.ini

ARG BUILD_DATE
ARG VERSION
LABEL build_version="version:- ${VERSION} Build-date:- ${BUILD_DATE}"
