#!/usr/bin/env bash

set -euo pipefail

PUID=${PUID:-1000}
PGID=${PGID:-1000}

groupmod -o -g "$PGID" www-data
usermod -o -u "$PUID" www-data

echo "
----------------------
GID/UID
----------------------
User uid:    $(id -u www-data)
User gid:    $(id -g www-data)
----------------------
"

nginx -v
echo "
----------------------
"

php -v

echo "
----------------------

"

mkdir -p \
  /config/keys \
  /config/log/{nginx,php} \
  /config/nginx/site-confs \
  /config/php/php-fpm.d \
  /run/{nginx,php-fpm} \
  /var/lib/nginx/tmp/client_body \
  /var/tmp/nginx

chown www-data:www-data /app
chown www-data:www-data /config
chown www-data:www-data /defaults

chown -R www-data:www-data \
    /config \
    /var/{lib,tmp}/nginx \
    /run/{nginx,php-fpm}

chmod -R g+w \
    /config/nginx

# Copy the default config file if they don't exist
find /config/nginx/site-confs -maxdepth 0 -empty \
  -exec cp /defaults/nginx/site-confs/default.conf.sample /config/nginx/site-confs/default.conf \;

find /config/php/php-fpm.d -maxdepth 0 -empty \
  -exec cp /defaults/php/php-fpm.d/www.conf.sample /config/php/php-fpm.d/www2.conf \;

if [[ ! -f /config/nginx/ssl.conf ]]; then
    cp /defaults/nginx/ssl.conf.sample /config/nginx/ssl.conf
fi

# Update Timezone
export TZ=${TZ:-"Europe/Berlin"}
echo "$TZ" >  /etc/timezone
echo -e "[global]\ndate.timezone=$TZ\n" > /etc/php/conf.d/timezone.ini


#######
# Generating random keys for self signed ssl
#######

if [[ ! -f /config/keys/cert.key && ! -f /config/keys/cert.crt ]]; then
  SUBJECT="/C=DE/ST=BE/L=Berlin/O=Carlos Gomes/OU=CG Server/CN=*"
  echo "Generating self-signed keys in /config/keys, you can replace these with your own keys if required"
  openssl req -new -x509 -days 3650 -nodes -out /config/keys/cert.crt -keyout /config/keys/cert.key -subj "$SUBJECT"
  chown -R www-data:www-data /config/keys/
fi

# copy pre-generated dhparams
if [[ ! -f /config/nginx/dhparams.pem ]]; then
    cp /defaults/nginx/dhparams.pem.sample /config/nginx/dhparams.pem
    chown -R www-data:www-data /config/nginx/dhparams.pem
fi

#######
# Executing the services
#######

## enable job control
set -m

su www-data -ps /bin/bash -c "nginx -e /config/log/nginx/error.log"
su www-data -ps /bin/bash -c "php-fpm -F" &

if [ -z "$@" ]; then
  fg %1
else
  "$@"
fi
