name: Build and publish
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [8.1, 7.1]
        include:
          - tag: 8.1
            target: build

          - tag: 7.1
            target: build_71
    env:
      TAG: ${{ matrix.tag }}-alpine
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build PHP ${{ matrix.tag }}
        run: make ${{ matrix.target }}

      - name: Publish PHP ${{ matrix.tag }}
        run: make publish
